### ISSUE TITLE
The "name" field is not properly extracted from the FVP engine

### ISSUE THREAD

**Issue by fushi002** [satan53x/SExtractor#118]
Hello,
I have extracted text from a specific game ([link](https://vndb.org/v2959)) that uses the FVP engine, but the "name" field is being extracted as "???".

Could you provide any solutions or assistance to resolve this issue?

[[hcb]HoshimemoEH_HD.zip](https://github.com/user-attachments/files/17725409/hcb.HoshimemoEH_HD.zip)

![image](https://github.com/user-attachments/assets/c110e190-197c-4f70-ad68-adb9ca5c9802)

**Comment by satan53x** [comment]
Updated, and the param is: `extraData=13BB,98E40,080808021A2009000E`

**Comment by satan53x** [comment]
But, the FVP engine in SE is only used to translate to Chinese because the byte length is fixed.
If you wanna trans to English, you should use some other tool, such as: (Choose any one)
- https://github.com/Tabing010102/fvp
- https://github.com/regomne/chinesize/tree/master/FAVORITE/extText
- https://github.com/xmoezzz/rfvp/tree/main/disassembler
