### ISSUE TITLE
Moonhir repacking

### ISSUE THREAD

**Issue by Ronald181381** [satan53x/SExtractor#78]
I'm so sorry for the repeated disturbance, but I used the moonhir tool, the translation and conversion into .fbx went perfectly, but so far I haven't come across a tool to repack the fbx files into an fpk file

AE does have an option to repack into fpk, but that's for system c, not moonhir

**Comment by satan53x** [comment]
MoonHir can read .fbx file without repack, just put it into the game root folder.
But it will crash if just put .fbx file, because garbro decompress file when unpack.
So you need to compress .fbx file.

https://github.com/satan53x/SExtractor/tree/main/tools/MoonHir
Here's the tool. Rename the .fbx to .fbx.uncomp first.

**Comment by Ronald181381** [comment]
I had no idea you could do that
Thank you so much

**Comment by Brokye** [comment]
> I'm so sorry for the repeated disturbance, but I used the moonhir tool, the translation and conversion into .fbx went perfectly, but so far I haven't come across a tool to repack the fbx files into an fpk file
> 
> AE does have an option to repack into fpk, but that's for system c, not moonhir
What tool did you use to extract the text? Game crash after I change the text. Does it need to be the same length as the original text?
